PR to add files necessary for GitHub actions testing and test profile
lifebit-ai/prs pull request #22
Opened 2020-10-15 14:43 UTC by mmeier93

## This PR does the following:

- It adds files necessary for performing CI testing using GitHub actions (`ci.yml`, `test.config`)
- It adds a test profile in `nextflow.config`

## Comments:

Given that the PRS pipeline can work in 2 different ways (SAIGE output with test data present in repo VS GWAS catalogue data that has to be downloaded), I was not sure which method should be tested or whether both should be tested. For now, I just went with the SAIGE option, as there is testdata easily available.

2020-10-15 19:21 UTC, cgpu commented on .github/workflows/ci.yml
> +          nextflow run ${GITHUB_WORKSPACE} -profile test
Might be worth naming it

```Suggestion
          nextflow run ${GITHUB_WORKSPACE} -profile test_saige_base_gel_gwas_plink_target
```

2020-10-15 19:22 UTC, cgpu commented on nextflow.config
> +  test { includeConfig 'conf/test_saige_base_gel_gwas_plink_target.config' }
To match the change above:

```Suggestion
  test_saige_base_gel_gwas_plink_target { includeConfig 'conf/test_saige_base_gel_gwas_plink_target.config' }
```

2020-10-15 19:23 UTC, cgpu requested changes
Looks good to me, maybe it's worth renaming with the explicit test name you created to match across all diff places.

2020-10-15 19:38 UTC, mmeier93 commented
> Looks good to me, maybe it's worth renaming with the explicit test name you created to match across all diff places.

Thanks! 👍  I made the changes you suggested and the lasts 2 tests worked. There was however an error on the third before last which seemed to be related to the GitHub API failing? (https://github.com/lifebit-ai/prs/runs/1260958654?check_suite_focus=true).

2020-10-15 19:43 UTC, mmeier93 reviewed
Thanks! 👍

2020-10-16 10:03 UTC, cgpu approved these changes

2020-10-16 10:05 UTC, merged